version: '3.8'

services:
  app:
    build: .
    ports:
      - "8005:8005"
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=bybdbuser
      - SPRING_DATASOURCE_PASSWORD=saudara123
      - SECURITY_JWT_SECRET_KEY=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - SECURITY_JWT_EXPIRATION_TIME=86400000
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=taskdb
      - MYSQL_USER=bybdbuser
      - MYSQL_PASSWORD=saudara123
      - MYSQL_ROOT_PASSWORD=saudara123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Port untuk koneksi AMQP
      - "15672:15672" # Port untuk Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mysql_data:
